/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as PayIndexRouteImport } from './routes/pay.index'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDocsRouteImport } from './routes/_authenticated/admin/docs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users.index'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as ApiPublicCronSendRemindersRouteImport } from './routes/api/public/cron/send-reminders'
import { Route as ApiPublicPayOrderIdRouteImport } from './routes/api/public/pay.$orderId'
import { Route as ApiPublicPaymentsPollRouteImport } from './routes/api/public/payments/poll'
import { Route as ApiPublicSubscriptionWebhookRouteImport } from './routes/api/public/subscription/webhook'
import { Route as ApiPublicV1OrdersRouteImport } from './routes/api/public/v1/orders'
import { Route as ApiPublicV1InternalDispatchWebhooksRouteImport } from './routes/api/public/v1/internal/dispatch-webhooks'
import { Route as ApiPublicV1OrdersIdRouteImport } from './routes/api/public/v1/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDocsRoute = AuthenticatedAdminDocsRouteImport.update({
  id: '/admin/docs',
  path: '/admin/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronSendRemindersRoute =
  ApiPublicCronSendRemindersRouteImport.update({
    id: '/api/public/cron/send-reminders',
    path: '/api/public/cron/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayOrderIdRoute = ApiPublicPayOrderIdRouteImport.update({
  id: '/api/public/pay/$orderId',
  path: '/api/public/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsPollRoute = ApiPublicPaymentsPollRouteImport.update({
  id: '/api/public/payments/poll',
  path: '/api/public/payments/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscriptionWebhookRoute =
  ApiPublicSubscriptionWebhookRouteImport.update({
    id: '/api/public/subscription/webhook',
    path: '/api/public/subscription/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersRoute = ApiPublicV1OrdersRouteImport.update({
  id: '/api/public/v1/orders',
  path: '/api/public/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InternalDispatchWebhooksRoute =
  ApiPublicV1InternalDispatchWebhooksRouteImport.update({
    id: '/api/public/v1/internal/dispatch-webhooks',
    path: '/api/public/v1/internal/dispatch-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIdRoute = ApiPublicV1OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay/': typeof PayIndexRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/cron/send-reminders': typeof ApiPublicCronSendRemindersRoute
  '/api/public/pay/$orderId': typeof ApiPublicPayOrderIdRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/subscription/webhook': typeof ApiPublicSubscriptionWebhookRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRouteWithChildren
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/api/public/v1/internal/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/orders/$id': typeof ApiPublicV1OrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay': typeof PayIndexRoute
  '/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/cron/send-reminders': typeof ApiPublicCronSendRemindersRoute
  '/api/public/pay/$orderId': typeof ApiPublicPayOrderIdRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/subscription/webhook': typeof ApiPublicSubscriptionWebhookRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/api/public/v1/internal/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/orders/$id': typeof ApiPublicV1OrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay/': typeof PayIndexRoute
  '/_authenticated/admin/docs': typeof AuthenticatedAdminDocsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/cron/send-reminders': typeof ApiPublicCronSendRemindersRoute
  '/api/public/pay/$orderId': typeof ApiPublicPayOrderIdRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/subscription/webhook': typeof ApiPublicSubscriptionWebhookRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRouteWithChildren
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/api/public/v1/internal/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/orders/$id': typeof ApiPublicV1OrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/signup'
    | '/api-keys'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/pay/$orderId'
    | '/pay/'
    | '/admin/docs'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/api/public/health'
    | '/admin/'
    | '/admin/users/$id'
    | '/api/public/cron/send-reminders'
    | '/api/public/pay/$orderId'
    | '/api/public/payments/poll'
    | '/api/public/subscription/webhook'
    | '/api/public/v1/orders'
    | '/admin/users/'
    | '/api/public/v1/internal/dispatch-webhooks'
    | '/api/public/v1/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/signup'
    | '/api-keys'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/pay/$orderId'
    | '/pay'
    | '/admin/docs'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/api/public/health'
    | '/admin'
    | '/admin/users/$id'
    | '/api/public/cron/send-reminders'
    | '/api/public/pay/$orderId'
    | '/api/public/payments/poll'
    | '/api/public/subscription/webhook'
    | '/api/public/v1/orders'
    | '/admin/users'
    | '/api/public/v1/internal/dispatch-webhooks'
    | '/api/public/v1/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/api-keys'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/pay/$orderId'
    | '/pay/'
    | '/_authenticated/admin/docs'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscriptions'
    | '/api/public/health'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/users/$id'
    | '/api/public/cron/send-reminders'
    | '/api/public/pay/$orderId'
    | '/api/public/payments/poll'
    | '/api/public/subscription/webhook'
    | '/api/public/v1/orders'
    | '/_authenticated/admin/users/'
    | '/api/public/v1/internal/dispatch-webhooks'
    | '/api/public/v1/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  PayIndexRoute: typeof PayIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCronSendRemindersRoute: typeof ApiPublicCronSendRemindersRoute
  ApiPublicPayOrderIdRoute: typeof ApiPublicPayOrderIdRoute
  ApiPublicPaymentsPollRoute: typeof ApiPublicPaymentsPollRoute
  ApiPublicSubscriptionWebhookRoute: typeof ApiPublicSubscriptionWebhookRoute
  ApiPublicV1OrdersRoute: typeof ApiPublicV1OrdersRouteWithChildren
  ApiPublicV1InternalDispatchWebhooksRoute: typeof ApiPublicV1InternalDispatchWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pay/': {
      id: '/pay/'
      path: '/pay'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/docs': {
      id: '/_authenticated/admin/docs'
      path: '/admin/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AuthenticatedAdminDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/send-reminders': {
      id: '/api/public/cron/send-reminders'
      path: '/api/public/cron/send-reminders'
      fullPath: '/api/public/cron/send-reminders'
      preLoaderRoute: typeof ApiPublicCronSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay/$orderId': {
      id: '/api/public/pay/$orderId'
      path: '/api/public/pay/$orderId'
      fullPath: '/api/public/pay/$orderId'
      preLoaderRoute: typeof ApiPublicPayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/poll': {
      id: '/api/public/payments/poll'
      path: '/api/public/payments/poll'
      fullPath: '/api/public/payments/poll'
      preLoaderRoute: typeof ApiPublicPaymentsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscription/webhook': {
      id: '/api/public/subscription/webhook'
      path: '/api/public/subscription/webhook'
      fullPath: '/api/public/subscription/webhook'
      preLoaderRoute: typeof ApiPublicSubscriptionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders': {
      id: '/api/public/v1/orders'
      path: '/api/public/v1/orders'
      fullPath: '/api/public/v1/orders'
      preLoaderRoute: typeof ApiPublicV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/internal/dispatch-webhooks': {
      id: '/api/public/v1/internal/dispatch-webhooks'
      path: '/api/public/v1/internal/dispatch-webhooks'
      fullPath: '/api/public/v1/internal/dispatch-webhooks'
      preLoaderRoute: typeof ApiPublicV1InternalDispatchWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id': {
      id: '/api/public/v1/orders/$id'
      path: '/$id'
      fullPath: '/api/public/v1/orders/$id'
      preLoaderRoute: typeof ApiPublicV1OrdersIdRouteImport
      parentRoute: typeof ApiPublicV1OrdersRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedAdminDocsRoute: typeof AuthenticatedAdminDocsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedAdminDocsRoute: AuthenticatedAdminDocsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1OrdersRouteChildren {
  ApiPublicV1OrdersIdRoute: typeof ApiPublicV1OrdersIdRoute
}

const ApiPublicV1OrdersRouteChildren: ApiPublicV1OrdersRouteChildren = {
  ApiPublicV1OrdersIdRoute: ApiPublicV1OrdersIdRoute,
}

const ApiPublicV1OrdersRouteWithChildren =
  ApiPublicV1OrdersRoute._addFileChildren(ApiPublicV1OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  PayIndexRoute: PayIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCronSendRemindersRoute: ApiPublicCronSendRemindersRoute,
  ApiPublicPayOrderIdRoute: ApiPublicPayOrderIdRoute,
  ApiPublicPaymentsPollRoute: ApiPublicPaymentsPollRoute,
  ApiPublicSubscriptionWebhookRoute: ApiPublicSubscriptionWebhookRoute,
  ApiPublicV1OrdersRoute: ApiPublicV1OrdersRouteWithChildren,
  ApiPublicV1InternalDispatchWebhooksRoute:
    ApiPublicV1InternalDispatchWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
